name: 'Setup nf-test Environment'
description: 'Common setup steps for nf-test workflows'

inputs:
  aws_access_key_id:
    description: 'AWS Access Key ID'
    required: true
  aws_secret_access_key:
    description: 'AWS Secret Access Key'
    required: true
  load_rust_container:
    description: 'Whether to load the locally-built Rust container from artifacts (set to "true" when Rust code changed)'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Maximize build space
      shell: bash
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /usr/local/lib/android
        sudo rm -rf /opt/ghc
        sudo rm -rf /opt/hostedtoolcache/CodeQL
        sudo docker image prune --all --force
        sudo docker builder prune --all --force
        sudo apt-get remove -y '^aspnetcore-.*' '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' azure-cli google-chrome-stable firefox powershell mono-devel libgl1-mesa-dri
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h

    # Load Rust container AFTER docker prune (which would delete it if loaded earlier)
    - name: Download Rust container artifact
      if: ${{ inputs.load_rust_container == 'true' }}
      uses: actions/download-artifact@v4
      with:
        name: rust-container

    - name: Load Rust container into Docker
      if: ${{ inputs.load_rust_container == 'true' }}
      shell: bash
      run: gunzip -c rust-tools.tar.gz | docker load

    - name: Configure AWS CLI
      shell: bash
      run: |
        aws configure set aws_access_key_id ${{ inputs.aws_access_key_id }}
        aws configure set aws_secret_access_key ${{ inputs.aws_secret_access_key }}
        aws configure set default.region us-east-1

    - name: Login to ECR Public
      shell: bash
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Extract Nextflow version from config
      id: nf-version
      shell: bash
      run: |
        set -euo pipefail
        CONFIG_FILE="configs/profiles.config"
        if [[ ! -f "$CONFIG_FILE" ]]; then
          echo "ERROR: Config file not found: $CONFIG_FILE"
          exit 1
        fi
        VERSION=$(grep -oP "nextflowVersion\s*=\s*['\"]!>=\K[0-9]+\.[0-9]+\.[0-9]+" "$CONFIG_FILE" || true)
        if [[ -z "$VERSION" ]]; then
          echo "ERROR: Could not extract Nextflow version from $CONFIG_FILE"
          echo "Expected format: nextflowVersion = '!>=X.Y.Z'"
          exit 1
        fi
        if [[ ! "$VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "ERROR: Invalid version format: $VERSION"
          echo "Expected semantic version: X.Y.Z"
          exit 1
        fi
        echo "Extracted Nextflow version: $VERSION"
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Setup Nextflow
      uses: nf-core/setup-nextflow@v1
      with:
        version: ${{ steps.nf-version.outputs.version }}

    - name: Setup nf-test
      uses: nf-core/setup-nf-test@v1
