name: 'Setup Python Environment'
description: 'Set up Python with project dependencies from pyproject.toml'

inputs:
  additional_requirements:
    description: 'Path to additional requirements file to install'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Install additional dependencies
      if: inputs.additional_requirements != ''
      shell: bash
      run: pip install -r ${{ inputs.additional_requirements }}
